#!/usr/bin/env bash
# This script installs nginx on your server

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
