#!/usr/bin/env bash
# This script creates a backup of all your databases

mysqldump -uroot -p"$1" --all-databases > backup.sql
date=$(date "+%d-%m-%Y") 
backupFile="$date.tar.gz"
tar -cvzf "$backupFile" backup.mysql
